---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cmb-portfolio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ressafri/cmb-k8s-delete-me.git
    targetRevision: HEAD
    path: cmb-portfolio
  destination:
    server: https://kubernetes.default.svc
    # namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
